### ISSUE TITLE
Drop "xml2js" for "elementtree" dependency

### ISSUE THREAD

**Issue by jrobichaud** [aaccurso/grunt-bump-cordova#11]
Cordova uses `elementtree` to handle `config.xml` and `grunt-bump-cordova` uses `xml2js`.

Both libs output `config.xml` differently which causes unwanted file modifications depending of which command was used last. The best would be to reimplement grunt-bump-cordova using `elementtree` to avoid this kind of issue.

Ex: call `grunt bump` then `cordova plugin add <any_plugin> --save`

**Comment by GabLeRoux** [comment]
Solution would be to rewrite this part:
https://github.com/aaccurso/grunt-bump-cordova/blob/master/tasks/bump.js#L101-L132

where `parseString` and `xmlBuilder` are being used :)

**Comment by aaccurso** [comment]
Any volunteer?

**Comment by jrobichaud** [comment]
I'll do it.

**Comment by aaccurso** [comment]
Merged in version 0.1.7
