### ISSUE TITLE
Fatal error: Can not find a version to bump in src/config.xml

### ISSUE THREAD

**Issue by humphreybc** [aaccurso/grunt-bump-cordova#6]
I'm getting this error when trying to run this through my PhoneGap config.xml file.

Here's my Gruntfile configuration:

    options: {
      files: ['package.json', 'src/manifest.json', 'src/config.xml'],
      commit: false,
      createTag: false,
      push: false,
      globalReplace: false,
      regExp: false
    }

And here's my config.xml:

    <?xml version="1.0" encoding="UTF-8" ?>
    <widget xmlns="http://www.w3.org/ns/widgets"
      xmlns:gap="http://phonegap.com/ns/1.0"
      id="com.phonegap.supersimpletasks"
      versionCode="312"
      version="3.1.2">

      <name>Super Simple Tasks</name>

      <description>
        The world’s simplest tasks app with offline support, an elegant design, and no account required! 
      </description>

      <author href="http://humphreybc.com" email="humphreybc@gmail.com">
        Benjamin Humphrey 
      </author>

      <gap:platform name="android" />

      <preference name="permissions" value="none" />
      <preference name="android-minSdkVersion" value="21" />

      <icon src="android-icon.png" />

      <access origin="*" />

      
      <plugin name="cordova-plugin-whitelist" version="1" />
      <allow-intent href="http://*/*" />
      <allow-intent href="https://*/*" />
      <allow-intent href="tel:*" />
      <allow-intent href="sms:*" />
      <allow-intent href="mailto:*" />
      <allow-intent href="geo:*" />
      <platform name="android">
        <allow-intent href="market:*" />
      </platform>
      <platform name="ios">
        <allow-intent href="itms:*" />
        <allow-intent href="itms-apps:*" />
      </platform>

    </widget>

**Comment by aaccurso** [comment]
Hi, I think modifying [this line](https://github.com/aaccurso/grunt-bump-cordova/blob/master/tasks/bump.js#L107) will help.
I don't currently have a working environment to test this.
Try changing your local copy of the script `bump.js`. Replace `/config(.)*\.xml$/` with `/(.)*config(.)*\.xml$/`.
Then please tell me if that works for you.

**Comment by aaccurso** [comment]
Closing since no feedback was given.
