### ISSUE TITLE
Why removing prerelease tag ?

### ISSUE THREAD

**Issue by Tibo75** [aaccurso/grunt-bump-cordova#9]
Hi,

when using a specific version (using 'setversion' option), why do you explicitly [remove the prerelease tag](https://github.com/aaccurso/grunt-bump-cordova/blob/master/tasks/bump.js#L113) ?

When bumping to 0.4.0-0, all other files get expected value except config.xml that results in 0.4.0.
So the 'exactVersionToSet' is not the version I get.. 

A fix or at least an option to force the expected value would be nice.

Thanks in advance!

**Comment by aaccurso** [comment]
Hi,

I'd be happy to merge a PR that can fix this.

Thanks!

**Comment by aaccurso** [comment]
Hello :)
Have you tried building an Android and iOS application with a pre-release tag?
Is it valid or does the build throw errors?
Thanks!

**Comment by Tibo75** [comment]
Hi,

no problem for Android but I'm not working yet with iOS (and don't have the appropriate environment), so I can't be sure. :/

FYI, we are using Git Flow as branching model and we use a lot the pre-release tag for intermediate branches (develop/release candidates/features/etc) keeping the standard notation (x.y.z) only for master and tagged releases. We take advantage of this package (forked and fixed this way) to bump all versions in package.json, bower.json and config.xml at the same time.

Without proposed fix, you may note that the bumped versions will differ from config.xml and other files when using the "setversion" option.
We are not calling it the same way (intermediate package calling yours with "setversion" variable defined), but you can reproduce easily the same issue we are facing this way :

1. Starting from this configuration:
package.json with version=0.1.0-0
bower.json with version=0.1.0-0
config.xml with version=0.1.0-0
 

2. Run _grunt bump --setversion=0.1.0-1_
>Version bumped to 0.1.0-1 (in package.json)
>Version bumped to 0.1.0-1 (in bower.json)
>Version bumped to 0.1.0-1 (in config.xml) **-> which will show up as wrong**


3. Read versions in files:
package.json contains version=0.1.0-1
bower.json contains version=0.1.0-1
config.xml contains version=**0.1.0**

This behavior leads to unconsistent data within files.

Thanks your time!

**Comment by aaccurso** [comment]
Yes, I understand the issue :)
I just had the impression it wasn't possible to build prerelease versions in Android, maybe it wasn't possible before and that's why I removed the prerelease.
Looks good to me.
Thanks for contributing!
